# Generated by Django 5.1.5 on 2026-08-17 10:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=120)),
                ('logo', models.CharField(max_length=8)),
                ('arr', models.BigIntegerField(default=0)),
                ('plan', models.CharField(max_length=80)),
                ('employees', models.IntegerField(default=0)),
                ('region', models.CharField(max_length=80)),
                ('csm', models.CharField(default='You', max_length=120)),
                ('health', models.IntegerField(default=0)),
                ('health_label', models.CharField(max_length=40)),
                ('health_trend', models.CharField(blank=True, default='', max_length=10)),
                ('renewal_date', models.DateTimeField()),
                ('renewal_status', models.CharField(max_length=40)),
                ('product_usage_summary', models.TextField(blank=True, default='')),
                ('strategic_notes', models.TextField(blank=True, default='')),
                ('mrr', models.BigIntegerField(default=0)),
                ('list_price', models.BigIntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('net_price', models.BigIntegerField(default=0)),
                ('billing_frequency', models.CharField(blank=True, default='', max_length=40)),
                ('payment_terms', models.CharField(blank=True, default='', max_length=40)),
                ('contract_start', models.DateField(blank=True, null=True)),
                ('last_renewal_date', models.DateField(blank=True, null=True)),
                ('customer_since', models.DateField(blank=True, null=True)),
                ('contract_pdf_url', models.CharField(blank=True, default='', max_length=300)),
                ('partner', models.CharField(blank=True, max_length=200, null=True)),
                ('partner_margin', models.IntegerField(default=0)),
                ('outstanding_balance', models.BigIntegerField(default=0)),
                ('champion', models.CharField(blank=True, default='', max_length=200)),
                ('exec_sponsor', models.CharField(blank=True, default='', max_length=200)),
                ('decision_makers', models.JSONField(blank=True, default=list)),
                ('primary_risk', models.TextField(blank=True, default='')),
                ('current_opportunity', models.TextField(blank=True, default='')),
                ('atlas_executive_summary', models.TextField(blank=True, default='')),
                ('atlas_confidence', models.IntegerField(default=0)),
                ('purchased_products', models.JSONField(blank=True, default=list)),
                ('seats_purchased', models.IntegerField(default=0)),
                ('seats_used', models.IntegerField(default=0)),
                ('dau', models.IntegerField(default=0)),
                ('wau', models.IntegerField(default=0)),
                ('mau', models.IntegerField(default=0)),
                ('feature_adoption', models.JSONField(blank=True, default=list)),
                ('api_usage_monthly', models.BigIntegerField(default=0)),
                ('storage_used_gb', models.FloatField(default=0)),
                ('storage_total_gb', models.FloatField(default=0)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('power_users', models.JSONField(blank=True, default=list)),
                ('inactive_users', models.JSONField(blank=True, default=list)),
                ('adoption_trend', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('owner', models.CharField(blank=True, default='', max_length=200)),
                ('last_updated', models.DateField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'policies',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price_per_seat', models.IntegerField(default=0)),
                ('monthly_per_seat', models.IntegerField(default=0)),
                ('flat_annual', models.IntegerField(default=0)),
                ('tier', models.CharField(blank=True, default='', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(blank=True, default='', max_length=120)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='atlas_api.company')),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('from_name', models.CharField(db_column='from', max_length=200)),
                ('subject', models.CharField(max_length=300)),
                ('snippet', models.TextField(blank=True, default='')),
                ('sentiment', models.CharField(blank=True, default='', max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='atlas_api.company')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=60)),
                ('date', models.DateField()),
                ('due_date', models.DateField()),
                ('amount', models.BigIntegerField()),
                ('status', models.CharField(max_length=20)),
                ('period', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='atlas_api.company')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('attendees', models.JSONField(blank=True, default=list)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_min', models.IntegerField(default=30)),
                ('type', models.CharField(blank=True, default='', max_length=40)),
                ('location', models.CharField(blank=True, default='', max_length=120)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='atlas_api.company')),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='atlas_api.company')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atlas_api.meeting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Brief',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brief', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='briefs', to='atlas_api.company')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atlas_api.meeting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('author', models.CharField(default='You', max_length=120)),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='atlas_api.company')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='atlas_api.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=300)),
                ('priority', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=40)),
                ('opened', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='atlas_api.company')),
            ],
            options={
                'ordering': ['-opened'],
            },
        ),
        migrations.CreateModel(
            name='WorkbenchCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=20)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='ready', max_length=20)),
                ('priority_rank', models.IntegerField(default=2)),
                ('intent', models.CharField(blank=True, default='', max_length=40)),
                ('priority', models.CharField(blank=True, default='', max_length=4)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('reason', models.TextField(blank=True, default='')),
                ('business_impact', models.TextField(blank=True, default='')),
                ('recommended_action', models.TextField(blank=True, default='')),
                ('estimated_seconds', models.IntegerField(default=30)),
                ('artifacts', models.JSONField(blank=True, default=dict)),
                ('edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('regenerated_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workbench_cards', to='atlas_api.company')),
            ],
            options={
                'ordering': ['priority_rank', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('owner', models.CharField(blank=True, default='', max_length=120)),
                ('due', models.CharField(blank=True, default='', max_length=80)),
                ('priority', models.CharField(blank=True, default='', max_length=4)),
                ('status', models.CharField(default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='atlas_api.company')),
                ('followup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='atlas_api.followup')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='atlas_api.workbenchcard')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
